from setuptools import setup, find_packages

setup(
    name="flojoy",
    packages=find_packages(exclude=["tests"]),
    version="0.1.5-dev1",
    license="MIT",
    description="Python client library for Flojoy.",
    author="flojoy",
    author_email="jack.parmer@proton.me",
    url="https://github.com/flojoy-io/flojoy-python",
    download_url="https://github.com/flojoy-io/flojoy-python/archive/refs/heads/main.zip",
    keywords=[
        "data-acquisition",
        "lab-automation",
        "low-code",
        "python",
        "scheduler",
        "topic",
    ],
    python_requires=">=3.10",
    install_requires=[
        "python-box",
        "requests",
        "networkx",
        "numpy",
        "redis",
        "rq",
        "scipy",
        "pandas",
        "pytest",
        "python-dotenv",
        "pyyaml",
        "plotly==5.8.2",
        "transformers>=4.26.0",
        "torch>=1.9",
        "torchvision>=0.10",
        "Pillow",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Build Tools",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
    ],
)
